# -*- coding: utf-8 -*-
"""exercises.ipynb

Automatically generated by Colab.

Original file is located at
    https://example.invalid/private-submission
"""

#  HW1 CS-3753-01T-202530

#Open the Google Colab file link in the pdf, exercises.ipynb. Open the file while signed in to a google account. Run the code by clicking the “Run all” button.

#String code

str1 = "Welcome to Python Programming"

print(str1)

print(str1[11:17])

print(str1[-5:])

str1 = str1 + '!!'

print(str1)

#List code

lst = []

lst.append(1)

lst.append(2)

lst.append(3)

lst.append(4)

print(lst)

lst.append((5, 6))

print(lst)

lst.append(['perfect', 'wonderful'])

print(lst)

lst += [[7, 8], [9, 10]]

print(lst)

lst += [8.5, 7, 'code', 'software']

print(lst)

print(lst[-5:])

del lst[3:7]

print(lst)

#Tuple code

Tuple1 = tuple([1, 2, 3, 4])

print(Tuple1)

Tuple2 = ('Python', 'for', 'kids')

print(Tuple2)

Tuple1 = Tuple1 + Tuple2

print(Tuple1)

print(Tuple1[3:])

#Dictionary code

Dict = {}

Dict[0] = 'Python'

Dict[1] = 'Programming'

Dict[2] = 'Funny'

print(Dict)

Dict[1] = 'is very'

print(Dict)

print(Dict.keys())

print(Dict.values())

del Dict[2]

print(Dict)

print(2 in Dict)

val_list = list(Dict.values())

print(val_list)