# -*- coding: utf-8 -*-
"""exercises.ipynb

Automatically generated by Colab.

Original file is located at
    https://example.invalid/private-submission
"""

# -*- coding: utf-8 -*-
import matplotlib.pyplot as plt
import numpy as np
#  HW3

#Open the Google Colab file link in the pdf, exercises.ipynb. Open the file while signed in to a google account.
#Run the code by clicking the run button by each question code. Make sure Mumps.csv and Measles.csv are uploaded into the Collab "session storage files" or else it won't read the csv data.
#If there are issues with the Colab not having the csv file, download and run the program in Jupyter Notebook and run it with the Mumps.csv and Measles.csv files in the correct location.

##%% Q1 Matrix multiplication
print("Question 1 **************************************")

# matrices
A = np.array([[2, 8, 4],
              [5, 4, 2]])

B = np.array([[4, 1],
              [6, 4],
              [5, 3]])

C = np.array([[4, 1, 2],
              [6, 4, 3],
              [5, 3, 4]])

D = np.array([[4, 1, 2],
              [6, 4, 3]])

# dot products and prints
print("A ⋅ B:")
try:
    result_AB = np.dot(A, B)
    print(result_AB)
except ValueError as e:
    print("Cannot compute A ⋅ B:", e)

print("\nA ⋅ C:")
try:
    result_AC = np.dot(A, C)
    print(result_AC)
except ValueError as e:
    print("Cannot compute A ⋅ C:", e)

print("\nA ⋅ D:")
try:
    result_AD = np.dot(A, D)
    print(result_AD)
except ValueError as e:
    print("Cannot compute A ⋅ D:", e)

##%% Q2
print("Question 2 **************************************")

# a. scatter x and y
x = np.array([50, 68, 74, 70, 65, 61, 63, 74, 62])
y = np.array([170, 193, 209, 185, 195, 188, 188, 202, 183])

plt.figure(figsize=(6, 4))
plt.scatter(x, y)
plt.xlabel("x")
plt.ylabel("y")
plt.title("a. Scatter Plot of x and y")
plt.grid(True)
plt.show()

# b. Define zscore to compute zscore of x and y
def zscore(arr):
    return (arr - np.mean(arr)) / np.std(arr)

z_x = zscore(x)
z_y = zscore(y)

print("b. Z-scores of x:", z_x)
print("b. Z-scores of y:", z_y)

# c. Scatter zscore of x and y
plt.figure(figsize=(6, 4))
plt.scatter(z_x, z_y)
plt.xlabel("Z-score of x")
plt.ylabel("Z-score of y")
plt.title("c. Scatter Plot of Z-scores of x and y")
plt.grid(True)
plt.show()

# d. Pearson correlation
# Custom Pearson correlation using z-scores
pearson_custom = np.mean(z_x * z_y)

# Pearson correlation using numpy's corrcoef
pearson_numpy = np.corrcoef(x, y)[0, 1]

print("d. Pearson correlation coefficient (me):", pearson_custom)
print("d. Pearson correlation coefficient (numpy):", pearson_numpy)

if np.isclose(pearson_custom, pearson_numpy):
    print("d. The results are the same.")
else:
    print("d. The results differ.")

##%% Q3
print("Question 3 **************************************")
# x and y data
x = np.array([50, 68, 74, 70, 65, 61, 63, 74, 62, 80])
y = np.array([170, 193, 209, 185, 195, 188, 188, 202, 183, 1000])

# a. Scatter plot x and y
plt.figure()
plt.scatter(x, y)
plt.title('Scatter plot of x and y')
plt.xlabel('x')
plt.ylabel('y')
plt.grid(True)
plt.show()

# b. Pearson corrcoef
pearson_corr = np.corrcoef(x, y)[0, 1]
print("b. Pearson correlation coefficient:", pearson_corr)

# c. Spearman rank corrcoef
from scipy.stats import rankdata

x_rank = rankdata(x)
y_rank = rankdata(y)
spearman_corr = np.corrcoef(x_rank, y_rank)[0, 1]
print("c. Spearman rank correlation coefficient:", spearman_corr)

##%% Q4
print("Question 4 **************************************")
from scipy.stats import norm

# Generate data for the CDF plot
x = np.linspace(-4, 4, 1000)
cdf = norm.cdf(x)

# Plot the Standard Normal CDF
plt.plot(x, cdf, label='Standard Normal CDF', color='blue')
plt.axvline(x=0.5, color='green', linestyle='--', label='x = 0.5')
plt.axvline(x=-0.5, color='red', linestyle='--', label='x = -0.5')
plt.title('Standard Normal Cumulative Distribution Function')
plt.xlabel('X')
plt.ylabel('CDF')
plt.grid(True)
plt.legend()
plt.show()

# Calculate CDF values
cdf_0_5 = norm.cdf(0.5)
cdf_neg_0_5 = norm.cdf(-0.5)
probability = cdf_0_5 - cdf_neg_0_5
sym_prob = 2 * cdf_0_5 - 1

# Print the results in required format
print(f"a. norm.cdf(0.5) - norm.cdf(-0.5) = {cdf_0_5:.4f} - {cdf_neg_0_5:.4f} = {probability:.4f}")
print(f"b. 2*({cdf_0_5:.4f}) - 1 = {sym_prob:.4f}")

##%% Q5
print("Question 5 **************************************")
from scipy.stats import norm

# a
print("5a. If X ~ N(μ, σ²) and X' = aX + b, then:")
print("    X' ~ N(aμ + b, a²σ²)")

# b
print("\n5b. If X ~ N(μ, σ²), then standard normal Z is:")
print("    Z = (X - μ) / σ")

# c
mu = 5
sigma = 3
x1 = 2
x2 = 7

p1 = norm.cdf(x2, loc=mu, scale=sigma)
p2 = norm.cdf(x1, loc=mu, scale=sigma)
prob_c = p1 - p2

print("\n5c. P(2 <= X <= 7) where X ~ N(5, 9):")
print(f"    Convert X to standard normal: Z = (X - {mu}) / {sigma}")
print(f"    P(2 <= X <= 7) = P(({x1}-{mu})/{sigma} <= Z <= ({x2}-{mu})/{sigma})")
print(f"    = P({(x1 - mu)/sigma:.2f} <= Z <= {(x2 - mu)/sigma:.2f})")
print(f"    = {p1:.4f} - {p2:.4f} = {prob_c:.4f}")

# d Standard normal
z1 = -1.5
z2 = 1.5

p3 = norm.cdf(z2)
p4 = norm.cdf(z1)
prob_d = p3 - p4

print("\n5d. P(-1.5 <= X <= 1.5) where X ~ N(0, 1):")
print(f"    = P({z1} <= Z <= {z2})")
print(f"    = {p3:.4f} - {p4:.4f} = {prob_d:.4f}")

##%% Q6
print("Question 6 **************************************")
print("P(A ∪ B) = P(A) + P(B) - P(A ∩ B)")
print("P(A|B) = P(A ∩ B) / P(B)")
print("P(A ∩ B) = P(B) × P(A|B)")
print("If A and B are independent, P(A ∩ B) = P(A) × P(B)")

##%% Q7
print("Question 7 **************************************")
# sample space 8 die
sample_space = list(range(1, 9))  # d ∈ {1, 2, ..., 8}

#  events that hapen
event_even = [d for d in sample_space if d % 2 == 0]         # d is even
event_less_than_5 = [d for d in sample_space if d < 5]       #d < 5
event_both = [d for d in sample_space if (d % 2 == 0) and (d < 5)]  #A ∩ B

#probabilities
P_even = len(event_even) / len(sample_space)                # P(A)
P_less_than_5 = len(event_less_than_5) / len(sample_space)  # P(B)
P_both = len(event_both) / len(sample_space)                # P(A ∩ B)

# independence check for P(A ∩ B) == P(A) * P(B)
is_independent = P_both == P_even * P_less_than_5

# outputs
print("Sample space:", sample_space)
print("Event A (even numbers):", event_even)
print("Event B (numbers < 5):", event_less_than_5)
print("Event A ∩ B (even and < 5):", event_both)
print("P(A) =", P_even)
print("P(B) =", P_less_than_5)
print("P(A ∩ B) =", P_both)
print("P(A) * P(B) =", P_even * P_less_than_5)
print("Are A and B independent?", is_independent)

##%% Q8
print("Question 8 **************************************")
# probabilities
P_F = 0.95          # fair dice
P_L = 0.05          # loaded dice
P_6_given_F = 1/6   # six w/ fair die
P_6_given_L = 0.5   # six w/ loaded die

# 4 sixes in a row
P_4s_given_F = P_6_given_F ** 4
P_4s_given_L = P_6_given_L ** 4

print("P(4 sixes | Fair die):", P_4s_given_F)
print("P(4 sixes | Loaded die):", P_4s_given_L)

# all prob of 4 sixes
P_4s = P_4s_given_F * P_F + P_4s_given_L * P_L
print("Total probability of 4 sixes together: ", P_4s)

# bayes
P_L_given_4s = (P_4s_given_L * P_L) / P_4s
print("Probability the die is loaded, with 4 sixes:", P_L_given_4s)

##%% Q9
print("Question 9 **************************************")
# probabilities
P_disease = 1 / 10000
P_no_disease = 1 - P_disease

P_pos_given_disease = 0.999  # real positive rate
P_pos_given_no_disease = 0.0002  # fake positive rate

P_neg_given_disease = 1 - P_pos_given_disease  # fake negative rate
P_neg_given_no_disease = 1 - P_pos_given_no_disease  # true negative rate

# a. for if positive test actually has disease
P_pos = (P_pos_given_disease * P_disease) + (P_pos_given_no_disease * P_no_disease)
P_disease_given_pos = (P_pos_given_disease * P_disease) / P_pos
print("a. Probability that someone who tests positive has the disease:", P_disease_given_pos)

# b. for if negative test has disease
P_neg = (P_neg_given_disease * P_disease) + (P_neg_given_no_disease * P_no_disease)
P_no_disease_given_neg = (P_neg_given_no_disease * P_no_disease) / P_neg
print("b. Probability that someone who tests negative does not have the disease:", P_no_disease_given_neg)

# close all existing floating figures
plt.close('all')

### Q10
print("Question 10 **************************************")
##%% load data
import pandas as pd
import matplotlib.pyplot as plt

measles = pd.read_csv('Measles.csv', header=None).values
mumps = pd.read_csv('Mumps.csv', header=None).values

# a. plot annual total measles cases in each year
plt.figure()
plt.title('a. NYC measles cases')

# 1. Your code is here
years = measles[:, 0]
annual_totals = measles[:, 1:].sum(axis=1)
plt.plot(years, annual_totals, marker='*', linestyle='-', color='b')
plt.xlabel('Year')
plt.ylabel('Number of cases')

plt.show()



##%% b. bar plot average mumps cases for each month of the year
import numpy as np

plt.figure()
plt.title('b. Average monthly mumps cases')

# 2. Your code is here
monthly_averages = mumps[:, 1:].mean(axis=0)
months = np.arange(1, 13)  # Month numbers 1 to 12

plt.bar(months, monthly_averages)
plt.xlabel('Month')
plt.ylabel('Average number of cases')
plt.xticks([2, 4, 6, 8, 10, 12])  # Only label even-numbered months

plt.show()




##%% c. scatter plot monthly mumps cases against measles cases
mumpsCases = mumps[:, 1:].reshape(41*12)
measlesCases = measles[:, 1:].reshape(41*12)

plt.figure()
plt.title('c. Monthly mumps vs measles cases')

# 3. Your code is here
plt.scatter(mumpsCases, measlesCases)
plt.xlabel('Number of Mumps Cases')
plt.ylabel('Number of Measles Cases')

plt.show()




##%% d. plot monthly mumps cases against measles cases in log scale
plt.figure()
plt.title('d. Monthly mumps vs measles cases (log scale)')

# 4. Your code is here
plt.loglog(mumpsCases, measlesCases, marker='o', linestyle='none', markersize=3)
plt.xlabel('Number of Mumps Cases')
plt.ylabel('Number of Measles Cases')

plt.show()




##%% e. Why would we want to plot the y axis in logarithm scale instead of linear scale

# 5. Your code is here
answer = 'We would do this because the Y value can represent varying magnitudes in values very well. It shows patterns and exponential growth in visual ways, especially important for skewed data or curves.'
print('\n\nAnswer to e: ' + answer)