# -*- coding: utf-8 -*-
"""exercises.ipynb

Automatically generated by Colab.

Original file is located at
    https://example.invalid/private-submission
"""

#  HW1 CS-3753-01T-202530

#Open the Google Colab file link in the pdf, exercises.ipynb. Open the file while signed in to a google account.
#Run the code by clicking the run button by each question code. Make sure fdata.csv is uploaded into the Collab "session storage files" or else it won't read the csv data.
#If there are issues with the Colab not having the csv file, download and run the program in Jupyter Notebook and run it with the fdata.csv file in the correct location.



#Q1

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv(
    'fdata.csv',
    sep=',',
    parse_dates=['Date'],
    index_col='Date'
)

df.plot()
plt.ylabel('Price')
plt.tight_layout()
plt.show()

#Q2

import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.dates as mdates

data = [
    ('2016-10-03', 772.559998),
    ('2016-10-04', 776.429993),
    ('2016-10-05', 776.469971),
    ('2016-10-06', 776.859985),
    ('2016-10-07', 775.080017)
]

# builds dataframe with pandas
df = pd.DataFrame(data, columns=['Date', 'Close'])
df['Date'] = pd.to_datetime(df['Date'])
df.set_index('Date', inplace=True)

# plots points
fig, ax = plt.subplots()
ax.plot(df.index, df['Close'], color='red', marker='o', label='Close')

# sets ticks and formatting
ax.set_xticks(df.index)
ax.xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m-%d'))

# sets titles and labels
ax.set_title('Closing stock value of Alphabet inc.')
ax.set_xlabel('Date')
ax.set_ylabel('Closing Value')

# configures grid
ax.grid(which='major', linewidth=1, color='red')
ax.minorticks_on()
ax.grid(which='minor', linewidth=0.6, linestyle=':')

plt.tight_layout()
plt.show()

#Q3

import matplotlib.pyplot as plt

# data import
languages = ['Java', 'Python', 'PHP', 'JavaScript', 'C#', 'C++']
popularity = [22.2, 17.6, 8.8, 8.0, 7.7, 6.7]

#plots data
fig, ax = plt.subplots()
bars = ax.bar(languages, popularity, color='blue')

#titles and labels
ax.set_title('Popularity of Programming Languages Worldwide, Oct 2017 compared to a year ago')
ax.set_xlabel('Languages')
ax.set_ylabel('Popularity')

# major ticks
ax.set_xticks(range(len(languages)))
ax.set_xticklabels(languages)
ax.set_yticks(range(0, 21, 5))  # doesnt show values past 20, like the example

# minor ticks
ax.set_yticks(range(0, 21, 1), minor=True)
ax.set_xticks([i + 0.5 for i in range(len(languages) - 1)], minor=True)

# sets ticks
ax.minorticks_on()

# onfigures grid
ax.grid(which='major', axis='both', linewidth=1, color='red')
ax.grid(which='minor', axis='both', linestyle=':', linewidth=0.5)

plt.tight_layout()
plt.show()

#Q4

import matplotlib.pyplot as plt

#data import
languages = ['Java', 'Python', 'PHP', 'JS', 'C#', 'C++']
popularity = [22.2, 17.6, 8.8, 8.0, 7.7, 6.7]

# Plotting
fig, ax = plt.subplots()
ax.barh(languages, popularity, color='green')

# titles and labels
ax.set_title('Popularity of Programming Languages Worldwide, Oct 2017 compared to a year ago')
ax.set_xlabel('Popularity')
ax.set_ylabel('Language')

# labels x axis up to 20
ax.set_xlim(0, 25)
ax.set_xticks([0, 5, 10, 15, 20])
ax.set_xticks(range(0, 26, 1), minor=True)
plt.minorticks_on()

plt.grid(which='major', linestyle='-', linewidth=0.8, color='red')
plt.grid(which='minor', linestyle=':', linewidth=0.5)

plt.tight_layout()
plt.show()

#Q5

import matplotlib.pyplot as plt

#group 1 data
weight1 = [67, 57.2, 59.6, 59.64, 55.8, 61.2, 60.45, 61, 56.23, 56]
height1 = [101.7, 197.6, 98.3, 125.1, 113.7, 157.7, 136, 148.9, 125.3, 114.9]

#group 2 data
weight2 = [61.9, 64, 62.1, 64.2, 62.3, 65.4, 62.4, 61.4, 62.5, 63.6]
height2 = [152.8, 155.3, 135.1, 125.2, 151.3, 135, 182.2, 195.9, 165.1, 125.1]

#group 3 data
weight3 = [68.2, 67.2, 68.4, 68.7, 71, 71.3, 70.8, 70, 71.1, 71.7]
height3 = [165.8, 170.9, 192.8, 135.4, 161.4, 136.1, 167.1, 235.1, 181.1, 177.3]

#scatter plot, stars, exapmple colors
plt.scatter(weight1, height1, color='red', marker='*')
plt.scatter(weight2, height2, color='green', marker='*')
plt.scatter(weight3, height3, color='blue', marker='*')

# Labels and title
plt.title('Group Wise Weight vs Height')
plt.xlabel('Weight')
plt.ylabel('Height')

plt.tight_layout()
plt.show()